name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "30 1 * * 1" # Weekly on Monday at 01:30 UTC

permissions: read-all

jobs:
  analysis:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # upload SARIF
      id-token: write        # publish results
      actions: read          # detect dangerous workflows
      contents: read         # read repo
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: scorecard-sarif
          path: results.sarif
          retention-days: 5

      - name: Upload to Code Scanning
        uses: github/codeql-action/upload-sarif@b5ebac6f4c00c8ccddb7cdcd45fdb248329f808a # v3
        with:
          sarif_file: results.sarif
